[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pedia-coach"
  to = "/.netlify/functions/pedia-coach"
  status = 200

[[redirects]]
  from = "/api/send-broadcast"
  to = "/.netlify/functions/send-broadcast"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
