import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const port = parseInt(process.env.PORT || '3000', 10);

app.use(express.json({ limit: '10mb' }));

// CORS headers for all incoming requests
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }
  next();
});

// =========================================================================
// 1. Text-to-Speech (TTS) Endpoint - Google Cloud & Google GenAI TTS
// =========================================================================
const handleLessonTts = async (req: express.Request, res: express.Response) => {
  try {
    const { title, text } = req.body || {};
    const apiKey =
      process.env.GEMINI_API_KEY ||
      process.env.VITE_GEMINI_API_KEY ||
      process.env.GOOGLE_GENAI_API_KEY ||
      process.env.GOOGLE_API_KEY;

    if (!apiKey) {
      return res.status(500).json({
        success: false,
        error: 'GEMINI_API_KEY is not configured in server environment.',
      });
    }

    const ai = new GoogleGenAI({ apiKey });
    const cleanExcerpt = (text || '').slice(0, 1600);
    const textToSpeak = `${title ? `${title}. ` : ''}${cleanExcerpt}`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash-lite-tts',
      contents: textToSpeak,
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: 'Kore', // Warm, clear, natural educational narrator voice
            },
          },
        },
      },
    });

    const audioPart = response.candidates?.[0]?.content?.parts?.find(
      (p: any) => p.inlineData?.data
    );

    if (!audioPart?.inlineData?.data) {
      return res.status(502).json({
        success: false,
        error: 'No audio generated by the Google TTS engine',
      });
    }

    return res.status(200).json({
      success: true,
      audioBase64: audioPart.inlineData.data,
      mimeType: audioPart.inlineData.mimeType || 'audio/wav',
    });
  } catch (error: any) {
    return res.status(500).json({ success: false, error: error.message });
  }
};

app.post('/api/lesson-tts', handleLessonTts);
app.post('/.netlify/functions/lesson-tts', handleLessonTts);

// =========================================================================
// 2. Pedia AI Coach Endpoint
// =========================================================================
const handlePediaCoach = async (req: express.Request, res: express.Response) => {
  try {
    const { query, lessonTitle, lessonContent, moduleTitle } = req.body || {};
    if (!query) {
      return res.status(400).json({ error: 'Query is required' });
    }

    const apiKey =
      process.env.GEMINI_API_KEY ||
      process.env.VITE_GEMINI_API_KEY ||
      process.env.GOOGLE_GENAI_API_KEY ||
      process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      return res.status(500).json({
        success: false,
        error: 'GEMINI_API_KEY is not configured in server environment.',
      });
    }

    const ai = new GoogleGenAI({ apiKey });
    const prompt = `Student Question: "${query}"

Current Context:
- Course Module: ${moduleTitle || 'Early Childhood Development'}
- Active Lesson: ${lessonTitle || 'Core Lesson'}
- Lesson Content Excerpt:
${(lessonContent || '').slice(0, 1800)}

Instructions:
1. Provide an authoritative, clear, encouraging explanation as Pedia, the Baby First Health learning coach.
2. ABSOLUTELY NO EMOJIS under any circumstances. Emojis look unprofessional and like AI slop. Use clean professional text, bullet points, and concise paragraphs instead.
3. If the student asks for quiz answers or direct test options, do NOT give answers; instead guide them to understand the clinical concepts.
4. STRICT PROFESSIONAL INTEGRITY & BOUNDARIES: You are exclusively an early childhood education academic mentor. Under NO circumstances engage in romantic remarks, flirting, sexual banter, perverse inquiries, or off-topic personal conversations. If a user inputs anything non-educational, firmly decline and redirect back to the active lesson.
5. Format using clean markdown (paragraphs and bullet points).`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: prompt,
      config: {
        systemInstruction: `You are Pedia, the official Early Childhood Development (ECD) learning coach for Baby First Health. You assist healthcare, caregiver, and early childhood students. Keep all answers professional, encouraging, evidence-based (WHO/AAP/UNICEF), and concise. ABSOLUTELY FORBIDDEN: Do not use emojis anywhere in your response.`,
      },
    });

    return res.status(200).json({ success: true, reply: response.text || '' });
  } catch (error: any) {
    return res.status(500).json({ success: false, error: error.message });
  }
};

app.post('/api/pedia-coach', handlePediaCoach);
app.post('/.netlify/functions/pedia-coach', handlePediaCoach);

// =========================================================================
// 3. Broadcast Email Endpoint
// =========================================================================
const handleBroadcast = async (req: express.Request, res: express.Response) => {
  try {
    const data = req.body || {};
    const apiKey = process.env.RESEND_API_KEY;
    if (apiKey) {
      const { Resend } = await import('resend');
      const resend = new Resend(apiKey);
      const recipients = data.recipients || [];
      const fromAddress = process.env.RESEND_FROM_EMAIL || 'Baby First Health <updates@babyfirsthealth.com>';
      const result = await resend.emails.send({
        from: fromAddress,
        to: data.isTest ? recipients[0] : recipients,
        subject: data.payload.subject,
        html: `<p>${data.payload.body}</p>`,
      });
      return res.status(200).json({ success: true, result });
    }
    return res.status(200).json({
      success: true,
      simulated: true,
      message: 'Email broadcast simulated (configure RESEND_API_KEY to deliver live).',
    });
  } catch (err: any) {
    return res.status(500).json({ success: false, error: err.message });
  }
};

app.post('/api/send-broadcast', handleBroadcast);
app.post('/.netlify/functions/send-broadcast', handleBroadcast);

// =========================================================================
// 4. Vite Middleware (Dev) & Static Serving (Prod)
// =========================================================================
const startServer = async () => {
  const isProd = process.env.NODE_ENV === 'production';

  if (!isProd) {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true, hmr: process.env.DISABLE_HMR !== 'true' },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.resolve(__dirname, 'dist');
    app.use(express.static(distPath));
    app.get('*', (_req, res) => {
      res.sendFile(path.resolve(distPath, 'index.html'));
    });
  }

  app.listen(port, '0.0.0.0', () => {
    console.log(`Server listening on http://0.0.0.0:${port} (${isProd ? 'production' : 'development'})`);
  });
};

startServer();
